services:
  dev:
    build:
      context: ..
      dockerfile: DockerFile
    command: sleep infinity
    volumes:
      - ../.:/workspace
    env_file:
      - ../.env
    ports:
      - 8001:8000
    # Configure environment variables
    environment:
      XDEBUG_CONFIG: "client_host=127.0.0.1 client_port=9003"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
      MAILER_DSN: "smtp://maildev:1025"
      DATABASE_URL: "mysql://root:${DB_PASSWORD}@db_server:3306/${DB_DATABASE}?serverVersion=11.2.4-MariaDB&charset=utf8mb4"

  db_server:
    image: mariadb:11.2
    restart: always
    ports:
      - "33016:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8101:80
    env_file:
      - ../.env
    environment:
      PMA_HOST: db_server

  maildev:
    image: maildev/maildev
    ports:
      - "1081:1080"
      - "1026:1025"
    env_file:
      - ../.env

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
    env_file:
      - ../.env

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    env_file:
      - ../.env

volumes:
  db_data:
  redis-insight:
